name = "Vanilla+"
author = "Grayson Gantek"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1540efd18e40d3277593c914d8f39aa583c0127eae0f6318669c9dcce5ad44d1"

[versions]
fabric = "0.19.5"
minecraft = "26.1.2"
