name = "Vanilla+"
author = "Grayson Gantek"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "575ba5aca800528aa61419b16210f8b748c9569b6f631bbbcc675ecb0cde4040"

[versions]
fabric = "0.19.5"
minecraft = "26.1"
